### ISSUE TITLE
replace Typeform

### ISSUE THREAD

**Issue by JigmeDatse** [Datse-Multimedia-Productions/autismjobs#7]
Replace the typeform form with something running locally.  It's dangerously slow.  
- [x] Create Own Form (#9 handles this)
- [ ] Create Processing of the Form (#16 is working on this)
- [ ] Create Editing Script (#17 is part of this)

**Comment by JigmeDatse** [comment]
Currently working on it on branch `feature/ourform`

**Comment by JigmeDatse** [comment]
Depends on #5 to go any further right now.  Need to move on that before really being able to move more on this.

**Comment by JigmeDatse** [comment]
This needs to have processing, and editing enabled.  Those need to be two new issues.

**Comment by JigmeDatse** [comment]
This needs to be done before we remove the `/index.*` files.  So this is depended on by #24

**Comment by JigmeDatse** [comment]
This can be closed.

**Comment by JigmeDatse** [comment]
Leaving closed, despite the fact we don't currently have this fully functional, we do have it enough functional as to not really need to handle this as an open issue.
